In [4]:
#libs utilizadas:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.tree import export_text

In [5]:
# Definindo o Data frame e verificando cabe√ßalho:

df = pd.read_csv("Video_Games_Sales_as_at_22_Dec_2016.csv")

df.head(5)

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8.0,322.0,Nintendo,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8.0,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# Removendo colunas de n√£o interesse:

columns_to_remove = ['Publisher', 'Critic_Score', 'Critic_Count', 'User_Score', 'User_Count', 'Developer', 'Rating']
df = df.drop(columns=columns_to_remove, axis=1)

# Verificando se as colunas foram devidamente removidas:

df.head(5)

,Name,Platform,Year_of_Release,Genre,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,Wii Sports,Wii,2006.0,Sports,41.36,28.96,3.77,8.45,82.53
1,Super Mario Bros.,NES,1985.0,Platform,29.08,3.58,6.81,0.77,40.24
2,Mario Kart Wii,Wii,2008.0,Racing,15.68,12.76,3.79,3.29,35.52
3,Wii Sports Resort,Wii,2009.0,Sports,15.61,10.93,3.28,2.95,32.77
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,11.27,8.89,10.22,1.00,31.37

In [8]:
# Renomeando as colunas:

df.rename(columns={
    'Name':'nome',
    'Platform': 'plataforma',
    'Year_of_Release': 'ano_do_release',
    'Genre': 'genero',
}, inplace=True)

df.head()

,nome,plataforma,ano_do_release,genero,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,Wii Sports,Wii,2006.0,Sports,41.36,28.96,3.77,8.45,82.53
1,Super Mario Bros.,NES,1985.0,Platform,29.08,3.58,6.81,0.77,40.24
2,Mario Kart Wii,Wii,2008.0,Racing,15.68,12.76,3.79,3.29,35.52
3,Wii Sports Resort,Wii,2009.0,Sports,15.61,10.93,3.28,2.95,32.77
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,11.27,8.89,10.22,1.00,31.37

In [10]:
# Separando as caracter√≠sticas (X) e os r√≥tulos (y)
X = df[['genero']]
y = df['Global_Sales']

# Definindo os intervalos e as classes correspondentes
intervals = [-1, 1, 5, float('inf')]
classes = ['baixas vendas', 'm√©dias vendas', 'altas vendas']

# Atribuindo classes √†s vendas globais usando a fun√ß√£o cut
y = pd.cut(y, bins=intervals, labels=classes, right=False)

# Convertendo os dados categ√≥ricos em num√©ricos usando one-hot encoding
X = pd.get_dummies(X)

# Dividindo os dados em conjunto de treinamento e conjunto de teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Criando o modelo da √°rvore de decis√£o
model = DecisionTreeClassifier()

# Treinando o modelo
model.fit(X_train, y_train)

# Fazendo previs√µes no conjunto de teste
y_pred = model.predict(X_test)

# Avaliando a precis√£o do modelo
accuracy = accuracy_score(y_test, y_pred)
print("Precis√£o:", accuracy)

Precis√£o: 0.8803827751196173

In [11]:
# Criando o modelo da √°rvore de decis√£o
model = DecisionTreeClassifier()

# Treinando o modelo
model.fit(X_train, y_train)

# Imprimindo a √°rvore de decis√£o
tree_text = export_text(model, feature_names=list(X.columns))
print(tree_text)

|--- genero_Adventure <= 0.50
|   |--- genero_Platform <= 0.50
|   |   |--- genero_Shooter <= 0.50
|   |   |   |--- genero_Strategy <= 0.50
|   |   |   |   |--- genero_Misc <= 0.50
|   |   |   |   |   |--- genero_Puzzle <= 0.50
|   |   |   |   |   |   |--- genero_Simulation <= 0.50
|   |   |   |   |   |   |   |--- genero_Fighting <= 0.50
|   |   |   |   |   |   |   |   |--- genero_Racing <= 0.50
|   |   |   |   |   |   |   |   |   |--- genero_Role-Playing <= 0.50
|   |   |   |   |   |   |   |   |   |   |--- genero_Action <= 0.50
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- genero_Action >  0.50
|   |   |   |   |   |   |   |   |   |   |   |--- class: baixas vendas
|   |   |   |   |   |   |   |   |   |--- genero_Role-Playing >  0.50
|   |   |   |   |   |   |   |   |   |   |--- class: baixas vendas
|   |   |   |   |   |   |   |   |--- genero_Racing >  0.50
|   |   |   |   |   |   |   |   |   |--- class: baixas vendas
|   |   |   |   |   |   |   |--- genero_Fighting >  0.50
|   |   |   |   |   |   |   |   |--- class: baixas vendas
|   |   |   |   |   |   |--- genero_Simulation >  0.50
|   |   |   |   |   |   |   |--- class: baixas vendas
|   |   |   |   |   |--- genero_Puzzle >  0.50
|   |   |   |   |   |   |--- class: baixas vendas
|   |   |   |   |--- genero_Misc >  0.50
|   |   |   |   |   |--- class: baixas vendas
|   |   |   |--- genero_Strategy >  0.50
|   |   |   |   |--- class: baixas vendas
|   |   |--- genero_Shooter >  0.50
|   |   |   |--- class: baixas vendas
|   |--- genero_Platform >  0.50
|   |   |--- class: baixas vendas
|--- genero_Adventure >  0.50
|   |--- class: baixas vendas